### ISSUE TITLE
The animation caching is failed if zip is missed

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-mob#250]
```
unzipit.min.js:20     GET https://mob.ra.dev.teqfw.com/animation/general/002/frames.zip 404 (Not Found)
ja @ unzipit.min.js:20
z.unzip @ unzipit.min.js:31
cacheImg @ IDB.mjs:196
cachePrg @ IDB.mjs:250
unzipit.min.js:20 Uncaught (in promise) Error: failed http request animation/general/002/frames.zip, status: 404: 
    at ja (unzipit.min.js:20:336)
    at async z.unzip (unzipit.min.js:31:310)
    at async cacheImg (IDB.mjs:196:32)
    at async cachePrg (IDB.mjs:250:33)
    at async Ra_Mob_Front_Mod_Cache_Img_IDB.processQueue (IDB.mjs:342:25)
```

**Comment by flancer64** [comment]
Добавил обработку исключения, если идёт попытка загрузки отсутствующего архива с кадрами. Выложил на live.
